/* Generated by Together */

package com.project.main.entity;

public interface I_Persintent
{
	public long fetch(Entity ent);
  	public long update(Entity ent);
	public long delete(Entity ent);
	public long insert(Entity ent);

}
